### ISSUE TITLE
Add benchmarks to repo

### ISSUE THREAD

**Issue by jastkand** [edelpero/lupa#6]
I didn't find benchmarks in repository. What do you think on adding them here? It would be easier for new contributors to run them.

**Comment by edelpero** [comment]
Hi @jastkand,

Thanks for the suggestions, but I want to keep the repo as small as possible.

I've specified which tool I used to perform the benchmarks and the results, that should be enough for someone that wants to perform benchmarks locally.

Otherwise we'll need to include a minimal Rails application to perform the benchmarks since has_scope only works with Rails.

Regards,
Ezequiel
